const products = [
  {
    id: 1,
    title: 'high-back bench',
    company: 'ikea',
    image: 'https://www.course-api.com/images/store/product-1.jpeg',
    price: 9.99,
  },
  {
    id: 2,
    title: 'albany table',
    company: 'marcos',
    image: 'https://www.course-api.com/images/store/product-2.jpeg',
    price: 79.99,
  },
  {
    id: 3,
    title: 'accent chair',
    company: 'caressa',
    image: 'https://www.course-api.com/images/store/product-3.jpeg',
    price: 25.99,
  },
  {
    id: 4,
    title: 'wooden table',
    company: 'caressa',
    image: 'https://www.course-api.com/images/store/product-4.jpeg',
    price: 45.99,
  },
  {
    id: 5,
    title: 'dining table',
    company: 'caressa',
    image: 'https://www.course-api.com/images/store/product-5.jpeg',
    price: 6.99,
  },
  {
    id: 6,
    title: 'sofa set',
    company: 'liddy',
    image: 'https://www.course-api.com/images/store/product-6.jpeg',
    price: 69.99,
  },
  {
    id: 7,
    title: 'modern bookshelf',
    company: 'marcos',
    image: 'https://www.course-api.com/images/store/product-7.jpeg',
    price: 8.99,
  },
  {
    id: 8,
    title: 'emperor bed',
    company: 'liddy',
    image: 'https://www.course-api.com/images/store/product-8.jpeg',
    price: 21.99,
  },
  {
    id: 9,
    title: 'utopia sofa',
    company: 'marcos',
    image: 'https://www.course-api.com/images/store/product-9.jpeg',
    price: 39.95,
  },
  {
    id: 10,
    title: 'entertainment center',
    company: 'liddy',
    image: 'https://www.course-api.com/images/store/product-10.jpeg',
    price: 29.98,
  },
  {
    id: 11,
    title: 'albany sectional',
    company: 'ikea',
    image: 'https://www.course-api.com/images/store/product-11.jpeg',
    price: 10.99,
  },
  {
    id: 12,
    title: 'leather sofa',
    company: 'liddy',
    image: 'https://www.course-api.com/images/store/product-12.jpeg',
    price: 9.99,
  },
];
